version: '3.8'

services:
  backend:
    image: todo-backend
    build:
      context: .
    ports:
      - "3001:3001"
    restart: always

  frontend:
    image: todo-frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
